{{- if .Values.sandboxManager.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-manager
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
  {{- with .Values.sandboxManager.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.sandboxManager.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - "*.{{ .Values.sandboxManager.e2b.domain }}"
      secretName: "{{ .Values.sandboxManager.ingress.certSecretName }}"
  rules:
    - host: "*.{{ .Values.sandboxManager.e2b.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sandbox-manager
                port:
                  number: {{ .Values.sandboxManager.service.port }}
{{- end }}
