{{- if .Values.sandboxManager.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acs-sandbox-manager.serviceAccountName" . }}
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}