apiVersion: v1
kind: Service
metadata:
  name: agent-sandbox-operator-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-sandbox-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "agent-sandbox-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kruise-sandbox-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: agent-sandbox-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /pod-bypass-sandbox
    failurePolicy: Fail
    name: mbypass-sbx.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    objectSelector:
      matchExpressions:
        - key: ops.alibabacloud.com/enable-auto-create-sandbox
          operator: In
          values:
            - "true"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: agent-sandbox-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /default-sandboxset
    failurePolicy: Fail
    name: md-sbs.kb.io
    rules:
      - apiGroups:
          - agents.kruise.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - sandboxsets
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kruise-sandbox-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: agent-sandbox-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-sandboxset
    failurePolicy: Fail
    name: v-sbs.kb.io
    rules:
      - apiGroups:
          - agents.kruise.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - sandboxsets
    sideEffects: None
