apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acs-sandbox-manager.fullname" . }}
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "acs-sandbox-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acs-sandbox-manager.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "acs-sandbox-manager.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.controller.hostNetwork | default false }}
      containers:
        - name: controller
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.controller.repository }}:{{ .Values.controller.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.pullPolicy }}
          command:
            - /root/sandbox-manager
          args:
            - -v={{ .Values.controller.logLevel }}
          ports:
            - containerPort: 8080
              name: http-manager
            - containerPort: 9002
              name: grpc-ext-proc
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: E2B_DOMAIN
              value: {{ .Values.e2b.domain }}
            - name: E2B_ADMIN_KEY
              value: {{ .Values.e2b.adminApiKey }}
            - name: E2B_ENABLE_AUTH
              value: {{ .Values.e2b.enableAuth | quote }}
            - name: INFRA
              value: {{ .Values.controller.infra }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: builtin-templates
              mountPath: /root/builtin_templates
        - name: envoy-proxy
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.proxy.repository }}:{{ .Values.proxy.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.pullPolicy }}
          args:
            - "--config-path /etc/envoy/envoy.yaml"
          readinessProbe:
            tcpSocket:
              port: 7788
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 7788
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
          {{- with .Values.proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: envoy-config
          configMap:
            name: sandbox-manager-envoy-config
        - name: builtin-templates
          configMap:
            name: sandbox-manager-builtin-templates
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
