{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "acs-sandbox-manager.fullname" . }}
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - "*.{{ .Values.e2b.domain }}"
      secretName: "{{ .Values.ingress.certSecretName }}"
  rules:
    - host: "*.{{ .Values.e2b.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "acs-sandbox-manager.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
