apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "acs-sandbox-manager.serviceAccountName" . }}
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "patch", "update"]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "agents.kruise.io" ]
    resources: [ "sandboxes" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "agents.kruise.io" ]
    resources: [ "sandboxes/status" ]
    verbs: [ "get", "update", "patch" ]
  - apiGroups: [ "agents.alibabacloud.com" ]
    resources: [ "sandboxes" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "agents.alibabacloud.com" ]
    resources: [ "sandboxes/status" ]
    verbs: [ "get", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acs-sandbox-manager.serviceAccountName" . }}
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acs-sandbox-manager.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acs-sandbox-manager.serviceAccountName" . }}
