apiVersion: v1
kind: Service
metadata:
  name: {{ include "acs-sandbox-manager.fullname" . }}
  labels:
    {{- include "acs-sandbox-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7788
      protocol: TCP
      name: http-envoy
  selector:
    {{- include "acs-sandbox-manager.selectorLabels" . | nindent 4 }}
