---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-sandboxset
  failurePolicy: Fail
  name: md-sbs.kb.io
  rules:
  - apiGroups:
    - agents.kruise.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sandboxsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-sandboxtemplate
  failurePolicy: Fail
  name: md-sbt.kb.io
  rules:
  - apiGroups:
    - agents.kruise.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - sandboxtemplates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sandboxset
  failurePolicy: Fail
  name: v-sbs.kb.io
  rules:
  - apiGroups:
    - agents.kruise.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sandboxsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sandboxtemplate
  failurePolicy: Ignore
  name: v-sbt.kb.io
  rules:
  - apiGroups:
    - agents.kruise.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - sandboxtemplates
  sideEffects: None
