# This rule is not used by the project sandbox-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the agents.kruise.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sandbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-editor-role
rules:
- apiGroups:
  - agents.kruise.io
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.kruise.io
  resources:
  - sandboxes/status
  verbs:
  - get
