# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
sandboxManager:
  enabled: true
  replicaCount: 1
  # namespace to deploy sandbox Pods / VMs
  namespace: default

  e2b:
    domain: "your.domain.com"
    enableAuth: false
    adminApiKey: "admin-987654321"

  controller:
    repository: acs-image-test-01-registry.cn-hangzhou.cr.aliyuncs.com/develop/sandbox-manager
    pullPolicy: IfNotPresent
    tag: develop-20251126201632
    logLevel: 1 # set to 5 to see debug logs, set to 7 to see proxy logs
    infra: sandbox-cr
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 2000m
        memory: 4Gi
    hostNetwork: false

  proxy:
    repository: registry-cn-hangzhou.ack.aliyuncs.com/ack-demo/envoy
    pullPolicy: IfNotPresent
    tag: "v1.33"
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 2000m
        memory: 4Gi

  service:
    type: ClusterIP
    port: 7788

  # This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ingress:
    className: nginx
    annotations: { }
    certSecretName: sandbox-manager-tls

sandboxOperator:
  replicaCount: 2
  logLevel: 5

  # Customize controlerManager
  image:
    controllerManager:
      repository: acs-image-test-01-registry.cn-hangzhou.cr.aliyuncs.com/develop/sandbox-controller
      # tag, if defined will use the given image tag, else Chart.AppVersion will be used
      tag: develop-20251128143857

  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: { }
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: { }
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels:
  alibabacloud.com/acs: 'true'
#  alibabacloud.com/compute-class: general-purpose
#  alibabacloud.com/compute-qos: default

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000


nodeSelector: { }

tolerations: [ ]

affinity: { }
