apiVersion: agents.kruise.io/v1alpha1
kind: Sandbox
metadata:
  labels:
    app.kubernetes.io/name: sandbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-sample
spec:
  template:
    spec:
      containers:
      - name: sandbox
        image: nginx:latest
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "alicloud-disk-ssd"
      resources:
        requests:
          storage: 10Gi
