# Sandbox manager image
- op: replace
  path: /spec/template/spec/containers/1/image
  value: sandbox-manager:latest

# Envoy proxy image
- op: replace
  path: /spec/template/spec/containers/0/image
  value: envoyproxy/envoy:v1.33-latest

# E2B Domain
- op: replace
  path: /spec/template/spec/containers/0/env/4/value
  value: replace.with.your.domain

# E2B API Key
- op: replace
  path: /spec/template/spec/containers/0/env/5/value
  value: some-api-key