apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-manager
  namespace: sandbox-system
  labels:
    component: sandbox-manager
    app.kubernetes.io/name: sandbox-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sandbox-manager
      app.kubernetes.io/name: sandbox-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        component: sandbox-manager
        app.kubernetes.io/name: sandbox-manager
    spec:
      serviceAccountName: sandbox-manager
      containers:
        - name: controller
          image: sandbox-manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - /sandbox-manager
          args:
            - -v=7
            - --zap-log-level=7
            - --system-namespace=sandbox-system
            - --peer-selector=component=sandbox-manager
            - --kube-client-qps=10000
            - --kube-client-burst=30000
            - --e2b-domain=replace.with.your.domain
            - --e2b-admin-key=some-api-key
            - --e2b-enable-auth=true
            - --e2b-max-timeout=2592000
          ports:
            - containerPort: 8080
              name: http-manager
            - containerPort: 9002
              name: grpc-ext-proc
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 7789
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 7789
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          env:
            - name: INFRA
              value: sandbox-cr
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
        - name: envoy-proxy
          image: envoyproxy/envoy:v1.33-latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config-path /etc/envoy/envoy.yaml"
          livenessProbe:
            tcpSocket:
              port: 7788
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 7788
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 7788
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 7788
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: envoy-config
          configMap:
            name: sandbox-manager-envoy-config