# Sandbox manager image
- op: replace
  path: /spec/template/spec/containers/0/image
  value: openkruise/sandbox-manager:latest

# Envoy proxy image
- op: replace
  path: /spec/template/spec/containers/1/image
  value: envoyproxy/envoy:v1.33-latest