apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-manager
  namespace: sandbox-system
  labels:
    component: sandbox-manager
    app.kubernetes.io/name: sandbox-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.replace.with.your.domain"
        - "replace.with.your.domain"
      secretName: sandbox-manager-tls
  rules:
    - host: "*.replace.with.your.domain"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sandbox-manager
                port:
                  number: 7788
    - host: "replace.with.your.domain"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sandbox-manager
                port:
                  number: 7788
