apiVersion: v1
kind: Service
metadata:
  name: sandbox-manager
  namespace: sandbox-system
  labels:
    control-plane: sandbox-manager
    app.kubernetes.io/name: sandbox-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 7788
      targetPort: 7788
      protocol: TCP
      name: http-envoy
  selector:
    control-plane: sandbox-manager
    app.kubernetes.io/name: sandbox-manager