apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-manager
  namespace: sandbox-system
  labels:
    control-plane: sandbox-manager
    app.kubernetes.io/name: sandbox-manager
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true